name: cricket_app
description: "A simple Cricket app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0
  video_player: ^2.9.2
  chewie: ^1.10.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  http: ^1.3.0
  better_player_plus: ^1.0.8
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  appinio_video_player: ^1.2.2
  firebase_core: ^3.11.0
  firebase_database: ^11.3.2
  firebase_auth: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/SportyFont.otf

  fonts:
    - family: SportyFont
      fonts:
        - asset: lib/assets/fonts/SportyFont.otf
