name: cricket_app
description: "A simple Cricket app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0
  video_player: ^2.9.2
  chewie: ^1.10.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  http: ^1.3.0
  better_player_plus: ^1.0.8
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  appinio_video_player: ^1.2.2
  firebase_core: ^3.11.0
  firebase_database: ^11.3.2
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  wakelock_plus: ^1.2.10
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.14.3    # Added flutter_launcher_icons here
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/icon/app_icon.png
  android: true
  ios: true
  web: false
  android_gravity: center
  fullscreen: true
  # Immediately remove splash when Flutter starts

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/icon/app_icon.png  # Added flutter_launcher_icons config

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/SportyFont.otf
    - lib/assets/icon/app_icon.png        # Updated path for the app icon

  fonts:
    - family: SportyFont
      fonts:
        - asset: lib/assets/fonts/SportyFont.otf
